language: go
go:
  - 1.11
compiler:
  - g++
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq libtesseract-dev libleptonica-dev tesseract-ocr-eng
env:
  global:
    - LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/lib
    - GO111MODULE=on
install:
  - go get -t -v ./...
script:
  - go test ./... -cover
